name: Create Signing Key

on:
workflow_dispatch:

jobs:
create-key:
runs-on: ubuntu-latest

steps:
  - name: Generate Key
    run: |
      keytool -genkeypair \
        -keystore aigf-signing.jks \
        -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
        -keypass "${{ secrets.KEYSTORE_PASSWORD }}" \
        -alias aigf \
        -keyalg RSA \
        -keysize 2048 \
        -validity 10000 \
        -dname "CN=AIGF, OU=Personal, O=AIGF, L=India, S=India, C=IN"

  - name: Encode Key
    run: |
      base64 -w 0 aigf-signing.jks > aigf-key.txt

  - name: Upload Key
    uses: actions/upload-artifact@v4
    with:
      name: AIGF-signing-key
      path: aigf-key.txt
      retention-days: 1
